# https://winkelwagen.de/2024/04/18/jekyll-github-pages-docker-add-dependencies/
services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/site
    ports:
      - "4000:4000"
